## Part a

In [6]:
import numpy as np

In [7]:
x = np.array([0.1, 0.2, 0.3, 0.4])
f_x = np.array([[-0.62049958], [-0.28398668], [0.00660095], [0.24842440]])

In [8]:
def divided_difference_table(x, f_x):
    n = len(x)
    # make n x n matrix
    table = np.zeros((n,n))
    
    # initialize first col
    for i in range(n):
        table[i][0] = f_x[i]
    
    # divided difference algorithm
    for j in range(1,n):
        for i in range(n-j):
            table[i][j] = (table[i+1][j-1] - table[i][j-1]) / (x[i+j] - x[i])
        
    return table

In [9]:
table = divided_difference_table(x, f_x)
table

array([[-0.62049958,  3.365129  , -2.2962635 , -0.47315167],
       [-0.28398668,  2.9058763 , -2.438209  ,  0.        ],
       [ 0.00660095,  2.4182345 ,  0.        ,  0.        ],
       [ 0.2484244 ,  0.        ,  0.        ,  0.        ]])

In [10]:
def newton_polynomial(x, x_pred, coefficients):
    total = 0
    n = len(x)
    for i in range(n):
        temp = coefficients[i]
        for j in range(i):
            temp *= x_pred-x[j]
        total += temp
        
    return total

In [11]:
coeffs = table[0]
x_pred = .25
pred = newton_polynomial(x, x_pred, coeffs)
pred

-0.13277477437500004

## Part b

In [12]:
x_b = np.append(x, .5)
f_x_b = np.append(f_x, 0.12832130)
x_b, f_x_b

(array([0.1, 0.2, 0.3, 0.4, 0.5]),
 array([-0.62049958, -0.28398668,  0.00660095,  0.2484244 ,  0.1283213 ]))

In [13]:
table = divided_difference_table(x_b, f_x_b)
table

array([[-6.20499580e-01,  3.36512900e+00, -2.29626350e+00,
        -4.73151667e-01, -1.29301442e+02],
       [-2.83986680e-01,  2.90587630e+00, -2.43820900e+00,
        -5.21937283e+01,  0.00000000e+00],
       [ 6.60095000e-03,  2.41823450e+00, -1.80963275e+01,
         0.00000000e+00,  0.00000000e+00],
       [ 2.48424400e-01, -1.20103100e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 1.28321300e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [14]:
coeffs = table[0]
x_pred = .25
pred = newton_polynomial(x_b, x_pred, coeffs)
pred

-0.14004798046875003

## Adding a new term changed the predicted value